import AudioExample from "../components/AudioExample";
import ImageSlot from "../components/ImageSlot";
import Slide from "../components/Slide";
import SlideHeader from "../components/SlideHeader";
import { audioEvidence } from "../content/evidence";
export default function Page() {
  return (
    <Slide
      label="Tonwerk: script to reviewed audio"
      notes="2 minutes including 12-second audio. Source scene: content/listening/a1/ls-essen-einkaufen-01.mp3 and associated YAML, data/audio-provenance/a1/ls-essen-einkaufen-01.json. Provenance records human approval bound to master bytes, no voice cloning/reference audio. Studio capture remains missing because browser access to local engine was blocked. Do not imply the old audio was generated by today\u2019s version of the UI. Audio auto-stops when leaving this slide. Transcript is available if sound fails."
      className="editorial"
    >
      <SlideHeader kicker="Create & operate" title="Tonwerk: script to reviewed audio" />
      <div className="tonwerk-layout">
        <ImageSlot
          id="tonwerk"
          alt="Tonwerk scene timeline and QA report"
          specification="Capture an existing populated scene in Mischung or Prüfung: dialogue timing, master playback and actual QA verdict. Exclude bearer tokens."
        />
        <div>
          <div className="audio-flow">
            <span>Script</span>
            <span>↓ render</span>
            <span>Automatic checks</span>
            <span>↓ human review</span>
            <strong>Published audio</strong>
          </div>
          <AudioExample />
          <p className="caption">
            {audioEvidence.duration}-second excerpt · A1 market-stall scene
            <br />
            Existing approved audio; no live generation
          </p>
        </div>
      </div>
    </Slide>
  );
}
